export const PRESETS = {
  restaurant: {
    label: 'Restaurant',
    icon: 'utensils',
    avg_bill: 85,
    table_turns: 2,
    services_per_day: 2,
    occupancy_rate: 0.75,
    food_cost_pct: 0.30,
    staff_per_20_tables: 6,
    kitchen_staff_per_20_tables: 4,
    admin_hours_week: 12,
    upsell_pct: 0.010,
    table_turn_improvement: 0.010,
    order_error_rate: 0.008,
  },
  cafe: {
    label: 'Café / Coffee Shop',
    icon: 'coffee',
    avg_bill: 18,
    table_turns: 3.5,
    services_per_day: 2,
    occupancy_rate: 0.65,
    food_cost_pct: 0.28,
    staff_per_20_tables: 3,
    kitchen_staff_per_20_tables: 2,
    admin_hours_week: 8,
    upsell_pct: 0.007,
    table_turn_improvement: 0.008,
    order_error_rate: 0.005,
  },
  bar: {
    label: 'Bar / Nightclub',
    icon: 'wine-glass',
    avg_bill: 45,
    table_turns: 4,
    services_per_day: 1,
    occupancy_rate: 0.70,
    food_cost_pct: 0.22,
    staff_per_20_tables: 5,
    kitchen_staff_per_20_tables: 2,
    admin_hours_week: 10,
    upsell_pct: 0.012,
    table_turn_improvement: 0.005,
    order_error_rate: 0.010,
  },
  fast_casual: {
    label: 'Fast-Casual / Takeaway',
    icon: 'bag-shopping',
    avg_bill: 22,
    table_turns: 6,
    services_per_day: 2,
    occupancy_rate: 0.80,
    food_cost_pct: 0.32,
    staff_per_20_tables: 4,
    kitchen_staff_per_20_tables: 3,
    admin_hours_week: 8,
    upsell_pct: 0.008,
    table_turn_improvement: 0.012,
    order_error_rate: 0.006,
  },
  hotel_restaurant: {
    label: 'Hotel Restaurant',
    icon: 'hotel',
    avg_bill: 120,
    table_turns: 1.5,
    services_per_day: 2,
    occupancy_rate: 0.65,
    food_cost_pct: 0.30,
    staff_per_20_tables: 8,
    kitchen_staff_per_20_tables: 5,
    admin_hours_week: 15,
    upsell_pct: 0.010,
    table_turn_improvement: 0.008,
    order_error_rate: 0.008,
  },
  bakery: {
    label: 'Bakery / Patisserie',
    icon: 'bread-slice',
    avg_bill: 12,
    table_turns: 5,
    services_per_day: 2,
    occupancy_rate: 0.60,
    food_cost_pct: 0.35,
    staff_per_20_tables: 2,
    kitchen_staff_per_20_tables: 3,
    admin_hours_week: 6,
    upsell_pct: 0.004,
    table_turn_improvement: 0.010,
    order_error_rate: 0.003,
  },
};

export const BUSINESS_TYPES = Object.keys(PRESETS);
